config/routes.rb
Rails.application.routes.draw do



  # 顧客用
# URL /customers/sign_in ...
devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    resources :pictures
    resources :contacts, only: [:index,:show]
  end

  scope module: 'public' do
    get root to: "homes#top"
    resources :pictures, only: [:index, :show]
    resources :contacts, only: [:new,:create]
    post 'contacts/confirm', to: 'contacts#confirm'
    post 'contacts/back', to: 'contacts#back'
    get 'contacts/complete', to: 'contacts#complete'
    
    get 'quizzes/top'
    get 'quizzes/privacy'
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :images, dependent: :destroy
  has_many :pictures, dependent: :destroy
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_one_attached :image
  belongs_to :genre

  validates :name, presence: true
  validates :genre_id, presence: true
  validates :image, presence: true
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  def index
    @contacts=Contact.order("id DESC")
  end

  def show
    @contact=Contact.find(params[:id])
  end
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/pictures_controller.rb
class Admin::PicturesController < ApplicationController
  def index
    @pictures=Picture.all
  end

  def show
    @picture=Picture.find(params[:id])
  end

  def new
    @picture=Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      flash[:notice] = "投稿に成功しました"
      redirect_to admin_pictures_path
    else
      render "new"
    end
  end

  def edit
    @picture=Picture.find(params[:id])

  end

  def update
    picture=Picture.find(params[:id])
    if picture.update(picture_params)
      flash[:notice] = "編集内容の保存に成功しました"
      redirect_to admin_picture_path(picture.id)
    else
      render "edit"
    end
  end

  def destroy
    picture=Picture.find(params[:id])
    if picture.destroy
      flash[:notice] = "イラストの削除に成功しました"
    else
      flash[:notice] = "イラストの削除に成功しました"
    end
    redirect_to admin_pictures_path
  end

  private
  def picture_params
   params.require(:picture).permit(:name,:genre_id,:introduction,:image)
  end

end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end


# 管理者のログイン後ページ遷移とログアウト先
  protected
  def after_sign_in_path_for(resource)
    admin_pictures_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/pictures_helper.rb
module Admin::PicturesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/admin/contacts/index.html.erb
<div class="container">
  <h3>お問い合わせ一覧</h3>
  <table class="table bg-white">
    <thead>
    <tr>
      <th>名前</th>
      <th>お問い合わせ内容</th>
      <th>日時</th>
    </tr>
    <tbody>
      <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.message.truncate(15) %></td>
        <td><%= contact.created_at.strftime('%Y/%m/%d %H:%M')  %></td>
        <td><%= link_to "詳細", admin_contact_path(contact.id) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/contacts/show.html.erb
<div class="container justify-content-center">
  <h3>お問い合わせ詳細</h3>
    <ul class="list list-unstyled">
      <li>ユーザー</li>
      <li class="bg-white"><%= @contact.name %>(<%= @contact.email %>)</li>
      <li>お問合せ内容</li>
      <div class="bg-white"><%= @contact.message %></div>
      <li><%= @contact.created_at.strftime('%Y/%m/%d %H:%M') %></li>
    </ul>
  </table>
  <%= link_to "お問合せ一覧へ戻る", admin_contacts_path,class: "btn btn:hover" %>
</div>

app/views/admin/pictures/edit.html.erb
<main class="mb-auto">
    <div class="container">

      <h3>イラスト編集</h3>
       <!--登録エラーメッセージ-->
      <% if @picture.errors.any? %>
        <%= @picture.errors.count %>件のエラーが発生しました
        <% @picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>


      <%= form_with model: @picture, url:admin_picture_path(@picture.id), method: :patch do |f| %>

        <ul>
          <li>
            <%= f.label :genre_id, "ジャンル名" %>
            <%= f.select :genre_id, {'Person': 1, 'Animal': 2, 'Others':3}, { include_blank: '選択してください'} %>
          </li>

          <li>
            <%= f.label :name, "イラスト名" %>
            <%= f.text_field :name %>
          </li>

          <li>
            <%= f.label :introduction, "イラスト説明" %>
            <%= f.text_area :introduction %>
          </li>

          <li>
            <%= image_tag @picture.image, size: "200x200" %><br>
            <%= f.label :image,"画像を変更" %>
            <%= f.file_field :image, accept: "image/*" %>
          </li>
        </ul>
        <%= f.submit "保存" %>
      <% end %>


    </div>
</div>

app/views/admin/pictures/index.html.erb
<main class="mb-auto">
    <div class="container">

        <h3>イラストギャラリー</h3>

        <%= flash[:notice] %>



        <% @pictures.each do |picture| %>
            <% if picture.image.attached? %>
                <%= link_to image_tag(picture.image, size: "200x200"),admin_picture_path(picture.id) %>
            <% else %>
                <%= link_to image_tag('no_image', size: "200x200"), admin_picture_path(picture.id) %>
            <% end %>
        <% end %>

    </div>
</div>

app/views/admin/pictures/new.html.erb
<main class="mb-auto">
    <div class="container">


      <h3>イラスト新規登録</h3>

      <!--登録エラーメッセージ-->
      <% if @picture.errors.any? %>
        <%= @picture.errors.count %>件のエラーが発生しました
        <% @picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>


      <%= form_with model: @picture, url:admin_pictures_path do |f| %>

        <ul>
          <li>
            <%= f.label :genre_id, "ジャンル名" %>
            <%= f.select :genre_id, {'Person': 1, 'Animal': 2, 'Others':3}, { include_blank: '選択してください'} %>
          </li>

          <li>
            <%= f.label :name, "イラスト名" %>
            <%= f.text_field :name %>
          </li>

          <li>
            <%= f.label :introduction, "イラスト説明" %>
            <%= f.text_area :introduction %>
          </li>

          <li>
            <%= f.label :image,"画像" %>
            <%= f.file_field :image, accept: "image/*" %>
          </li>
        </ul>
        <%= f.submit %>
      <% end %>

    </div>
</div>

app/views/admin/pictures/show.html.erb
<main class="mb-auto">
    <div class="container">


        <p><%= @picture.name %>のshowページ</p>

            <%= @picture.name %>
            <%= @picture.introduction %>

            <% if @picture.image.attached? %>
                <%= link_to image_tag(@picture.image, size: "400x400") %>
            <% else %>
                <%= link_to image_tag('no_image', size: "400x400") %>
            <% end %>

            <%= link_to "編集", edit_admin_picture_path(@picture.id) %>
            <%= link_to "削除", admin_picture_path(@picture.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
    </div>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<!--%- if devise_mapping.registerable? && controller_name != 'registrations' %>-->
<!--  %= link_to "Sign up", new_registration_path(resource_name) %><br />-->
<!--% end %>-->

<!--%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>-->
<!--  %= link_to "Forgot your password?", new_password_path(resource_name) %><br />-->
<!--% end %>-->

<!--%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>-->
<!--  %= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />-->
<!--% end %>-->

<!--%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>-->
<!--  %= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />-->
<!--% end %>-->

<!--%- if devise_mapping.omniauthable? %>-->
<!--  %- resource_class.omniauth_providers.each do |provider| %>-->
<!--    %= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />-->
<!--  % end %>-->
<!--% end %>-->

app/views/homes/top.html.erb
<h1>Home</h1>

<p>ユルリモエの部屋</p>

<h3>ペン字練習帳</h3>

<h3>LINEスタンプ</h3>

<h3>イラストギャラリー</h3>

<H3>イラスト依頼</H3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--fontawesomeの記述はstyle.cssの記述より前に書くこと-->
    <script src="https://kit.fontawesome.com/054f3bdfdc.js" crossorigin="anonymous"></script>
    
    <title>YururiMoe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--以下３行google font ひな明朝-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hina+Mincho&display=swap" rel="stylesheet">
    <!--以下1行google font Noto Serif Japanese-->
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@200&display=swap" rel="stylesheet">
    <!--以下Zen old mincho-->
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@200&family=Zen+Old+Mincho&display=swap" rel="stylesheet">

  </head>
<body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag'logo.png', width: '100' %></a>
          <h3>ユルリモエの部屋</h3>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

                <% if admin_signed_in? %>
                  <li class="nav-item">
                    <%= link_to 'イラスト一覧', admin_pictures_path, class: 'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'イラスト登録', new_admin_picture_path, class: 'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "お問い合わせ", admin_contacts_path, class: 'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link' %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to 'top', root_path, class: 'nav-link' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'gallery', pictures_path, class: 'nav-link' %>
                  </li class="nav-item">
                    <%= link_to 'contact', new_contact_path, class: 'nav-link' %>
                  <li>

                  </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <!--headerの境界線をモコモコさせたい（(ここから)）-->
      <div style="white-space: nowrap; overflow:hidden">
      <% 30.times do %>
        <span class="rounded-circle bg-white">　　　</span>
      <% end %>
      </div>
      <!--headerモコモコ(ここまで)-->
    <%= yield %>
      <div style="text-align:center;">
     <%= image_tag "foot-panda.png", width: "20%", class: "img-responsive" %>
      </div>
    </main>
    <footer class="pt-5 pb-4", style="background-color: #877b80;">
      <div class="container">
        <div class="row no-gutters">

          <div class="col-md-3"></div>
          <div class="col-md-4 my-1">
            <p class="text-light font-hina mb-1 text-center">ユルリモエの部屋</p>
            <ul class="p-0 list-unstyled">
              <li><%= link_to 'top', root_path, class: 'p-0 nav-link text-light text-center' %></li>
              <li><%= link_to 'gallery', pictures_path, class: 'p-0 nav-link text-light text-center' %></li>
              <li><%= link_to 'contact', new_contact_path, class: 'p-0 nav-link text-light text-center' %></li>
            </ul>
          </div>


          <div class="col-md-2">
            <p class="mb-1 text-pink fint-hina text-center">-----sns------</p>
            <ul class="p-0 list-unstyled text-light text-center">
              <li>
                <%= link_to 'https://www.instagram.com/yururi_moe/', class: "text-pink" do %>
                  <i class="fa-brands fa-instagram text-pink"></i> yururi moe
                <% end %>
              </li>
              <li class="text-pink">
                <%= link_to 'https://www.instagram.com/gura_tan_tan/', class: "text-pink" do %>
                  <i class="fa-brands fa-instagram text-pink"></i> guratan
                <% end %>
              </li>
              <li><p class="text-pink text-center">---------------</p></li>
            </ul>
          </div>

        </div>
      </div>
    </footer>
  </body>
</html>